#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);

defined('DATA_PATH') or define('DATA_PATH',__DIR__.'/../../data');

defined('CONF_PATH') or define('CONF_PATH',__DIR__.'/../../conf');

defined('DB_PATH') or define('DB_PATH',CONF_PATH.'/database');

//defined('DATA_PATH') or define('DATA_PATH',__DIR__.'/data');
//
//defined('DB_PATH') or define('DB_PATH',DATA_PATH.'/database');


defined('DEBUG') or define('DEBUG',true);

defined('PATH_PID') or define('PATH_PID',DATA_PATH.'/PID');

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/config/console.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);